Repository TeamGoodHands/MicroMacro, pull requests merged in 2025-06, with the labels that each got.

#38 シャンプー実装
  MicroMacro/Assets/Prefabs/Enemy.meta
  MicroMacro/Assets/Prefabs/Enemy/DamageBullet.prefab
  MicroMacro/Assets/Prefabs/Enemy/DamageBullet.prefab.meta
  MicroMacro/Assets/Prefabs/Enemy/PushPump.prefab
  MicroMacro/Assets/Prefabs/Enemy/PushPump.prefab.meta
  MicroMacro/Assets/Prefabs/Player.prefab
  MicroMacro/Assets/Scenes/Level/Main/TestLevel.unity
  MicroMacro/Assets/Scripts/CoreModule/ObjectPool/ObjectPool.cs
  MicroMacro/Assets/Scripts/CoreModule/Utility.meta
  MicroMacro/Assets/Scripts/CoreModule/Utility/ObjectExtensions.cs
  MicroMacro/Assets/Scripts/CoreModule/Utility/ObjectExtensions.cs.meta
  MicroMacro/Assets/Scripts/LevelEditor/Editor/ObjectPlacer.cs
  MicroMacro/Assets/Scripts/Module/Enemy.meta
  MicroMacro/Assets/Scripts/Module/Enemy/DamageBullet.cs
  MicroMacro/Assets/Scripts/Module/Enemy/DamageBullet.cs.meta
  MicroMacro/Assets/Scripts/Module/Enemy/PushPump.cs
  MicroMacro/Assets/Scripts/Module/Enemy/PushPump.cs.meta
  MicroMacro/Assets/Scripts/Module/Enemy/PushPumpHead.cs
  MicroMacro/Assets/Scripts/Module/Enemy/PushPumpHead.cs.meta
  MicroMacro/Assets/Scripts/Module/Player/Component/IDamageable.cs
  MicroMacro/Assets/Scripts/Module/Player/Component/IDamageable.cs.meta
  MicroMacro/Assets/Scripts/Module/Player/Component/PlayerStatus.cs
  MicroMacro/Assets/Scripts/Module/Player/Component/PlayerStatus.cs.meta
  MicroMacro/Assets/Scripts/Module/Player/Weapon/Shooter.cs
Labels: review

#40 Fix/hanging branch
  MicroMacro/Assets/Prefabs/General/HangingBranch.prefab
  MicroMacro/Assets/Scenes/Level/Main/TestLevel.unity
  MicroMacro/Assets/Scripts/Module/Gimmick/HangingBranch.cs
  MicroMacro/Assets/Scripts/Module/Gimmick/PlayerMovementBinder.cs
Labels: review

#50 スケールが0になるまで巻き戻すように修正
  MicroMacro/Assets/Scripts/Module/Scaling/ScaleRewinder.cs
Labels: enhancement, review

#55 ゲートギミックの作成とグレ関連少し修正
  MicroMacro/Assets/Contents/Materials/Gate.mat
  MicroMacro/Assets/Contents/Materials/Gate.mat.meta
  MicroMacro/Assets/Prefabs/General/DropBox.prefab
  MicroMacro/Assets/Prefabs/General/DropBox.prefab.meta
  MicroMacro/Assets/Prefabs/General/GateGimmick.prefab
  MicroMacro/Assets/Prefabs/General/GateGimmick.prefab.meta
  MicroMacro/Assets/Prefabs/Player.prefab
  MicroMacro/Assets/Scenes/Level/Main/TestLevel.unity
  MicroMacro/Assets/Scripts/Module/Gimmick/OpenGate.cs
  MicroMacro/Assets/Scripts/Module/Gimmick/OpenGate.cs.meta
  MicroMacro/Assets/Scripts/Module/Player/Weapon/BallSimulator.cs
  MicroMacro/Assets/Scripts/Module/Player/Weapon/Launcher.cs
  MicroMacro/Assets/Scripts/Module/Player/Weapon/Overlap.cs
  MicroMacro/Assets/Settings/LevelObjectDictionary.asset
Labels: feature, review
