Repository TeamGoodHands/MicroMacro, pull requests merged in 2025-08, with the labels that each got.

#95 スタック検知の実装と弾道予測線バグ修正
  MicroMacro/Assets/Contents/Materials/TriggerTest.mat
  MicroMacro/Assets/Contents/Materials/TriggerTest.mat.meta
  MicroMacro/Assets/Prefabs/General/BounceBox.prefab
  MicroMacro/Assets/Prefabs/Shooter/MacroGrenade.prefab
  MicroMacro/Assets/Prefabs/Shooter/MicroGrenade.prefab
  MicroMacro/Assets/Scenes/Level/Test/ScaleStackTest.unity
  MicroMacro/Assets/Scenes/Level/Test/ScaleStackTest.unity.meta
  MicroMacro/Assets/Scripts/CoreModule/Constants/Layer.cs
  MicroMacro/Assets/Scripts/Module/Player/Weapon/BallSimulator.cs
  MicroMacro/Assets/Scripts/Module/Player/Weapon/Bullet.cs
  MicroMacro/Assets/Scripts/Module/Player/Weapon/Launcher.cs
  MicroMacro/Assets/Scripts/Module/Scaling/OneSizeLargeScaler.cs
  MicroMacro/Assets/Scripts/Module/Scaling/OneSizeLargeScaler.cs.meta
  MicroMacro/Assets/Scripts/Module/Scaling/ScaleStackSensor.cs
  MicroMacro/Assets/Scripts/Module/Scaling/ScaleStackSensor.cs.meta
  MicroMacro/Assets/Scripts/Module/Scaling/Scaler.cs
  MicroMacro/Assets/Scripts/Module/Scaling/TwoAxisScaler.cs
  MicroMacro/ProjectSettings/DynamicsManager.asset
  MicroMacro/ProjectSettings/EditorBuildSettings.asset
  MicroMacro/ProjectSettings/TagManager.asset
Labels: feature, review

#102 テストプレイの感想収集機能実装
  .gitattributes
  MicroMacro/Assets/Contents/Fonts/NotoSansJP-Medium.ttf
  MicroMacro/Assets/Contents/Fonts/NotoSansJP-Medium.ttf.meta
  MicroMacro/Assets/Contents/Fonts/NotoSansJP-Medium_SDF.asset
  MicroMacro/Assets/Contents/Fonts/NotoSansJP-Medium_SDF.asset.meta
  MicroMacro/Assets/Contents/Model/Player/MainCharactor_0821.fbx.meta
  MicroMacro/Assets/Contents/Model/Player/hugu.001.png.meta
  MicroMacro/Assets/Contents/Model/Player/human_tx.png.meta
  MicroMacro/Assets/Resources/DOTweenSettings.asset
  MicroMacro/Assets/Scenes/Level/OutGame/Feedback.unity
  MicroMacro/Assets/Scenes/Level/OutGame/Feedback.unity.meta
  MicroMacro/Assets/Scenes/Level/Test/Feedback.unity
  MicroMacro/Assets/Scenes/Level/Test/Feedback.unity.meta
  MicroMacro/Assets/Scripts/Module/Application/FeedbackSender.cs
  MicroMacro/Assets/Scripts/Module/Application/FeedbackSender.cs.meta
  MicroMacro/Assets/TextMesh Pro/Resources/TMP Settings.asset
  MicroMacro/ProjectSettings/EditorBuildSettings.asset
  MicroMacro/ProjectSettings/ShaderGraphSettings.asset
Labels: feature, review

#108 1-1調整
  MicroMacro/Assets/Prefabs/BoundBox.prefab
  MicroMacro/Assets/Prefabs/BoundBox.prefab.meta
  MicroMacro/Assets/Prefabs/General/BounceBox.prefab
  MicroMacro/Assets/Prefabs/General/BounceBox1-1-1.prefab
  MicroMacro/Assets/Prefabs/General/BounceBox1-1-2.prefab
  MicroMacro/Assets/Prefabs/General/BounceBox1-1-3.prefab
  MicroMacro/Assets/Prefabs/General/BounceBox1-1-4.prefab
  MicroMacro/Assets/Prefabs/General/BounceBox1-1-5.prefab
  MicroMacro/Assets/Prefabs/General/BounceBox1-1-6.prefab
  MicroMacro/Assets/Prefabs/General/BounceBox1-2-1.prefab
  MicroMacro/Assets/Prefabs/General/BounceBox1-2-2.prefab
  MicroMacro/Assets/Prefabs/General/BounceBox1-2-3.prefab
  MicroMacro/Assets/Scenes/Level/Test/1-1Ver2.unity
Labels: planning

#116 ハッチングポストプロセス実装
  MicroMacro/Assets/Contents/ScreenSpaceHatching.meta
  MicroMacro/Assets/Contents/ScreenSpaceHatching/GaussianBlur.hlsl
  MicroMacro/Assets/Contents/ScreenSpaceHatching/GaussianBlur.hlsl.meta
  MicroMacro/Assets/Contents/ScreenSpaceHatching/ScreenSpaceHatching.shader
  MicroMacro/Assets/Contents/ScreenSpaceHatching/ScreenSpaceHatching.shader.meta
  MicroMacro/Assets/Contents/ScreenSpaceHatching/ScreenSpaceHatchingFeature.cs
  MicroMacro/Assets/Contents/ScreenSpaceHatching/ScreenSpaceHatchingFeature.cs.meta
  MicroMacro/Assets/Contents/ScreenSpaceHatching/ScreenSpaceHatchingPass.cs
  MicroMacro/Assets/Contents/ScreenSpaceHatching/ScreenSpaceHatchingPass.cs.meta
  MicroMacro/Assets/Contents/ScreenSpaceHatching/crosshatch-pattern.png
  MicroMacro/Assets/Contents/ScreenSpaceHatching/crosshatch-pattern.png.meta
  MicroMacro/Assets/Contents/Shader/BaseToon.shadergraph
  MicroMacro/Assets/Scenes/Level/Main/1-1Ver2.unity
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest.unity
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest.unity.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/FuguInner.mat
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/FuguInner.mat.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/FuguOuter.mat
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/FuguOuter.mat.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/MainCharactor_0821.fbx
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/MainCharactor_0821.fbx.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/hugu.001.png
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/hugu.001.png.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/human.mat
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/human.mat.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/human_tx.png
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/human_tx.png.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/idle_fly.002.anim
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/idle_fly.002.anim.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/ready_down_fly.anim
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/ready_down_fly.anim.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/ready_side_fly.001.anim
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/ready_side_fly.001.anim.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/ready_up_fly.001.anim
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/ready_up_fly.001.anim.meta
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/walk_fly.001.anim
  MicroMacro/Assets/Scenes/Level/Test/HatchingTest/walk_fly.001.anim.meta
  MicroMacro/Assets/Scenes/Template/LevelTemplate.scenetemplate
  MicroMacro/Assets/Settings/PC_Renderer.asset
  MicroMacro/ProjectSettings/EditorBuildSettings.asset
Labels: review

#117 SoundManager改良
  MicroMacro/Assets/Scripts/Module/Management/SoundManager.cs
Labels: enhancement, review
